version: '3.4'

networks:
  dev:
    driver: bridge

services:
  web-mvc: 
    image: docker.io/library/webmvc
    depends_on:
      - "app_db"
    container_name: webmvc-services
    ports: 
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile 
    environment:
      - ConnectionsStrings__DefaultConnection=Server=app_db;Port=5432;Database=ExpenseDB;User ID=postgres;Password=postgres;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev 

  app_db: 
    image: postgres:latest 
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ExpenseDB
    ports:
      - "5433:5432"
    restart: always 
    volumes:
      - app_data:/var/lib/postgres/data 
    networks:
      - dev 

volumes:
  app_data: